// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncmsfqctyasxfbccfjax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbXNmcWN0eWFzeGZiY2NmamF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzM1MDUsImV4cCI6MjA2NzQwOTUwNX0.cEGTlSxs2KrbwTwVdwzO8NU1o_fFcpbETZUwzaXTFho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});